### PR TITLE
save state in url

### PR DESCRIPTION
**Pull request by wolfv**
This is saving state in URL using `?blabla=whatever`.

I need to fix the React state so that it's properly doing things to the state when navigating back and forth.

I am thinking that using a single dict / object for pagesize, index and query is simpler in this case. Will try that tomorrow morning.

### CODE REVIEW

**Comment by hbcarlos** [comment]
`useTable` doesn't pick `initialState.pageIndex` when updating the table using a query.

image

Everything else works.

**Comment by wolfv** [comment]
yeah, I also still have issues with going back & forth.

**Comment by wolfv** [comment]
or actually it seems to work!

**Comment by wolfv** [comment]
I am using globalFiltering (manual) here now, and gotoPage(0) to go back to the first page when searching.

There is one additional issue where the fetchData is not cancelled... but we can look at that later on.

**Pull request merged**
