### PR TITLE
Add jupyter releaser

### PR DESCRIPTION
**Pull request by fcollonval**
- [x] Bump npm packages

### CODE REVIEW

**Comment by hbcarlos** [comment]
To bump the version, I added a simple script that runs `lerna version` and the python package takes the version from the `package.json` of the main app.

There are two small issues:
1- I made the `@quetz-fronted/builder` private because the latest version is 3.1.0 instead of 0.3.1 as every other package, so when bumping the version, it changes to 0.3.2 as every other package :( I'm not sure what to do with it.

2 - The `draft-changelog` step fails saying that there is a conflict when committing the changes see [here](https://github.com/mamba-org/quetz-frontend/runs/7776947697?check_suite_focus=true#step:4:399). I don't understand what is happening. If we skip the step in the `pyproject.toml` it works, and the changelog is updated in the artifacts.

**Comment by fcollonval** [comment]
> To bump the version, I added a simple script that runs `lerna version` and the python package takes the version from the `package.json` of the main app.

:+1: 

> There are two small issues: 1- I made the `@quetz-fronted/builder` private because the latest version is 3.1.0 instead of 0.3.1 as every other package, so when bumping the version, it changes to 0.3.2 as every other package :( I'm not sure what to do with it.

That package is gonna be required by extensions to build their final assets. So it cannot be made private. As we were luckily still in the criteria, I unpublished all versions. So it should be safe to publish a new version aligning it with the other packages.

> 2 - The `draft-changelog` step fails saying that there is a conflict when committing the changes see [here](https://github.com/mamba-org/quetz-frontend/runs/7776947697?check_suite_focus=true#step:4:399). I don't understand what is happening. If we skip the step in the `pyproject.toml` it works, and the changelog is updated in the artifacts.

There is a bug currently with the releaser - not related to this PR...: https://github.com/jupyter-server/jupyter_releaser/pull/360

**Comment by hbcarlos** [comment]
> That package is gonna be required by extensions to build their final assets. So it cannot be made private. As we were luckily still in the criteria, I unpublished all versions. So it should be safe to publish a new version aligning it with the other packages.

Thanks!! I made it public again.

**Comment by hbcarlos** [comment]
> There is a bug currently with the releaser - not related to this PR...: https://github.com/jupyter-server/jupyter_releaser/pull/360

Thanks, @fcollonval.

Can we merge this PR and try to make a release?
Is there a workaround for this issue?

**Review by fcollonval — COMMENTED** [review]
:+1: to merge

**Pull request merged**
